### ISSUE TITLE
Wrong color format is used...

### ISSUE THREAD

**Issue by rsglobal** [lineage-rpi/android_local_manifest#10]
Hi,

From your recent post:

> Wrong color format is used in some games (You can workaround this by disabling hw overlays. Settings -> Device Preferences -> Developer options -> Disable HW overlays or add ‘hwc.drm.use_overlay_planes=0’ to /system/build.prop for more permanent solution. This will of course decrease performance slightly.)

It should be immediately fixed :). Please describe steps-to-reproduce

**Comment by KonstaT** [comment]
I think this was first reported with games like Asphalt 8 and Minecraft. Pixel Wheels is a small game that doesn't need Play Services where this can also be reproduced (https://f-droid.org/en/packages/com.agateau.tinywheels.android/). Check screenshots on that page for correct colors.

It seems that red and blue are swapped. I suspect this is some issue with gbm gralloc as it doesn't happen on Pi 3 where I'm using minigbm.

**Comment by rsglobal** [comment]
Today I was able to reproduce this issue on rpi4, unfortunately Pixel Wheels aren't starting on sunxi.
I've created an issue on GD to track it: https://github.com/GloDroid/glodroid_manifest/issues/81

**Comment by rsglobal** [comment]
@KonstaT ,

Please try this MR:
https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/-/merge_requests/128

**Comment by KonstaT** [comment]
@rsglobal 

Great, thanks! Yes, this seems to fix the issue with Pixel Wheels at least.
