### ISSUE TITLE
Unable to build /e/ for RPi4

### ISSUE THREAD

**Issue by RudraSwat** [lineage-rpi/android_local_manifest#13]
Hi, I tried building /e/ 10 (based on Lineage 17.1) for the Raspberry Pi 4. I added the manifest to the `local_manifests` directory and ran `repo sync`. I then ran `brunch` and most of the rules were built successfully. However the last rule, `build bacon` failed (was unable to create a hard link from the built file to the current directory). The built ZIP file was missing from `out/target/product/rpi4`.

**Comment by KonstaT** [comment]
https://github.com/lineage-rpi/android_local_manifest/issues/8#issuecomment-625031841
