### ISSUE TITLE
using lineage-rpi's mesa and gbm_gralloc with AOSP source

### ISSUE THREAD

**Issue by Road-Drum** [lineage-rpi/android_local_manifest#14]
as the title suggest, I'd like to use lineage-rpi's mesa and gbm_gralloc for building android-rpi as the android-rpi's mesa and gbm_gralloc is unmaintained for months. I'm inexperienced with how android works so do i need to use lineage-rpi's minigbm and libdrm as well? target is to build AOSP tablet with `android-12.0.0_r2` or `android-s-v2-preview-1` source

feel free to close, but I hope anyone can give a bit of insight before that

**Comment by KonstaT** [comment]
It's for Android 11 so it won't work with Android 12 quite as is (you need a patch for bumping max platform-sdk-version to 31 which is in Mesa main https://gitlab.freedesktop.org/mesa/mesa/-/commit/f1c322c269f9cfef0c07a0735d142f56de76d4ab).

You would need Mesa, drm_hwcomposer, and minigbm from lineage-rpi. libdrm is not needed with Android 12 as it already has a version that is new enough (also only needed in Android 11 with Mesa 21.2.x but not for older versions).

Device specific changes how to integrate this into a build are pretty well documented in Mesa Android build system's version history (https://gitlab.freedesktop.org/mesa/mesa/-/commits/main/android) or look GloDroid (https://github.com/GloDroid) for reference as Roman has done the work to upstream the support.

**Comment by Road-Drum** [comment]
thanks. so minigbm is preferred over gbm_gralloc for android 11/lineage 18 onwards? I'm cross referencing with the latest available lineage-rpi manifest, which is lineage 17.

**Comment by KonstaT** [comment]
Yes, just switched to one that uses gbm_mesa and gralloc@4 API (https://github.com/lineage-rpi/android_external_minigbm/tree/lineage-18.1). Not seeing too many issues with it so that's what I'll be using moving forward with Android 12 as well.

Previous builds used gbm_gralloc by default and there was an option to switch to minigbm (https://github.com/lineage-rpi/android_external_minigbm/tree/lineage-18.1-20211011). Using both of these also require a patch on Mesa that I have available for 21.1.x and older (but not for 21.2.x).

**Comment by Road-Drum** [comment]
thanks. I've just finished repo syncing and ready to modify stuff as I'm adapting for android-rpi sources

so for graphics related in device.mk, do these changes right? 

```
PRODUCT_PACKAGES += \
-    android.hardware.graphics.allocator@2.0-impl \
-    android.hardware.graphics.allocator@2.0-service \
-    android.hardware.graphics.composer@2.1-impl \
-    android.hardware.graphics.composer@2.1-service \
-    android.hardware.graphics.mapper@2.0-impl-2.1

+    android.hardware.graphics.allocator@4.0-service.minigbm_gbm_mesa \
+    android.hardware.graphics.mapper@4.0-impl.minigbm_gbm_mesa

PRODUCT_PACKAGES += \
-    gralloc.gbm \
-    hwcomposer.drm \
+  gralloc.gbm_mesa
+  hwcomposer.drm_minigbm
    libGLES_mesa
```

I can't find v4.0 version of android.hardware.graphics.composer in `minigbm/gralloc4` and quick skimming in glodroid, it's an interface used with gbm_gralloc that is based on older hal. would like to hear input on this as I am unfamiliar with deep stuff like hals

manifest.xml

```
<manifest version="1.0" type="device">
    <hal format="hidl">
        <name>android.hardware.graphics.allocator</name>
        <transport>hwbinder</transport>
-        <version>2.0</version>
+        <version>4.0</version>
        <interface>
            <name>IAllocator</name>
            <instance>default</instance>
        </interface>
    </hal>
    <hal format="hidl">
        <name>android.hardware.graphics.mapper</name>
        <transport arch="32+64">passthrough</transport>
-        <version>2.1</version>
+       <version>4.0</version>
        <interface>
            <name>IMapper</name>
            <instance>default</instance>
        </interface>
    </hal>
-    <hal format="hidl">
-        <name>android.hardware.graphics.composer</name>
-        <transport>hwbinder</transport>
-        <version>2.1</version>
-        <interface>
-            <name>IComposer</name>
-            <instance>default</instance>
-        </interface>
-    </hal>
</manifest>
```

**Comment by KonstaT** [comment]
Have you built android-rpi before? I would suggest that you first make one build without any changes (with repos in android-rpi manifest) before making any changes of your own so that you know you can produce an image that boots. Do you have a serial console adapter? That would be really useful for logging if (or should I rather say when) something goes wrong.

What you have so far is in the right direction. You need to declare more Mesa packages in device.mk and it should be hwcomposer.drm instead. In manifest.xml you can drop the allocator/mapper entirely but composer should be left as it was (composer is for drm_hwcomposer, allocator/mapper is for whatever gralloc you're using). What you're still completely missing is changes in BoardConfig.mk to build the right Mesa drivers. You also need set some system properties (e.g. using PRODUCT_PROPERTY_OVERRIDES in device.mk) to select which HAL you're using (e.g. 'ro.hardware.hwcomposer=drm'). Android 12 is slightly stricter with SELinux but with selinux=permissive I think you can still get away without making any changes there.

I don't know what's the best approach trying to help you. Should I try to nudge you in the right direction and let you figure things out. Or just spoil all the fun in that for you and tell what is needed. :)

**Comment by Road-Drum** [comment]
> Have you built android-rpi before?

A few times in the past, sometimes it boot as expected and sometimes break though I was holding myself from being fully invested due to obvious rpi3 weakness. At most I only add opengapps and just build it for fun. there's a motivation with android-12-v2 due to tablet receiving significant UI changes which I can't wait to see it myself than waiting for newer arpi/lineage-rpi images

> What you have so far is in the right direction. You need to declare more Mesa packages in device.mk and it should be hwcomposer.drm instead. 

noted, I've switched back to hwcomposer.drm. are these the extra packages? glodroid uses this after digging its device-common.mk from device.mk

```
PRODUCT_PACKAGES += \
    libEGL_mesa \
    libGLESv1_CM_mesa \
    libGLESv2_mesa \
    libgallium_dri \
    libglapi \
```

while android-rpi uses `PRODUCT_SOONG_NAMESPACES += external/mesa3d` 

> In manifest.xml you can drop the allocator/mapper entirely but composer should be left as it was (composer is for drm_hwcomposer, allocator/mapper is for whatever gralloc you're using). 

noted.

> What you're still completely missing is changes in BoardConfig.mk to build the right Mesa drivers. You also need set some system properties (e.g. using PRODUCT_PROPERTY_OVERRIDES in device.mk) to select which HAL you're using (e.g. 'ro.hardware.hwcomposer=drm'). 

are the ones from lineage-17.1 enough? keeping it consistent as I'm using lineage-rpi's while android-rpi uses drm_gralloc

```
BOARD_GPU_DRIVERS := v3d kmsro
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_SCREEN_DENSITY := 240
TARGET_USE_V3D_KMSRO := true
```
override set and capped opengles to 3.1 as per mesamatrix for v3d
```
PRODUCT_PROPERTY_OVERRIDES += \
    ro.hardware.gralloc=gbm_mesa \
    ro.hardware.hwcomposer=drm \
    ro.opengles.version=196609 \
```

I'd like to add v3dv to the mix but as usual I have zero clue how it's mapped given android-rpi uses a different approach via override `ro.hardware.vulkan=rpi4` and product package `vulkan.rpi4`. for now there's no example that I could follow so I'll keep it as is and remove it if it conflicts

> Android 12 is slightly stricter with SELinux but with selinux=permissive I think you can still get away without making any changes there.

noted. android-rpi already has it to permissive

**Comment by KonstaT** [comment]
> there's a motivation with android-12-v2 due to tablet receiving significant UI changes which I can't wait to see it myself than waiting for newer arpi/lineage-rpi images

Hmm, GloDroid already had v0.7.0 release which was Android 12 but I don't know what happened to it. :o

> are these the extra packages?

Yes.

> while android-rpi uses `PRODUCT_SOONG_NAMESPACES += external/mesa3d`

Don't need that anymore (though it doesn't break anything even if you had it). Latest Mesa uses Meson build system so you need pretty up-to-date Meson with that (can be installed on Ubuntu at least as a snap package).

> are the ones from lineage-17.1 enough?

Old and outdated. Should be:
```
BOARD_MESA3D_USES_MESON_BUILD := true
BOARD_MESA3D_GALLIUM_DRIVERS := vc4 v3d
BOARD_MESA3D_VULKAN_DRIVERS := broadcom
```

`ro.hardware.gralloc` shouldn't be set to anything with gralloc@4.

> I'd like to add v3dv to the mix but as usual I have zero clue how it's mapped given android-rpi uses a different approach via override `ro.hardware.vulkan=rpi4` and product package `vulkan.rpi4`.

It's `vulkan.broadcom` now so also `ro.hardware.vulkan=broadcom`. No other changes needed on that part. Example here https://github.com/GloDroid/glodroid_manifest/issues/160#issuecomment-940197543

**Comment by Road-Drum** [comment]
thanks a lot. added vulkan based on that example. also: 

> `ro.hardware.gralloc`shouldn't be set to anything with gralloc@4.

so `ro.hardware.gralloc=minigbm_gbm_mesa`? 

anyway tried building and golang-protobuf broke. 

```
error: external/golang-protobuf/Android.gen.bp:1343:1: "golang-protobuf-testing-protocmp" depends on undefined module "go-cmp"
error: external/golang-protobuf/Android.gen.bp:1343:1: "golang-protobuf-testing-protocmp" depends on undefined module "go-cmp-cmpopts"

```
turns out google shipped a new protobuf for `android-12-v2-preview` 🙃 modules actually present but I'm not familiar with golang to fix it though

not sure borrowing the older protobuf from latest `android-12.0.0_r7` is a good idea. I'll probably checkout `android-12.0.0_r7` and just build android-rpi with that

**Comment by KonstaT** [comment]
> so `ro.hardware.gralloc=minigbm_gbm_mesa`?

No, nothing (better just remove it as no point in setting `ro.hardware.gralloc=`). It's a native HIDL HAL so you can't specify it like with 'old' HALs.

> I'll probably checkout `android-12.0.0_r7` and just build android-rpi with that

Yes, latest release branches should compile without any extra hassle or at least `android-12.0.0_r2` I have running does.

**Comment by Road-Drum** [comment]
> anyway tried building and golang-protobuf broke.

think I found the cause of the error, go-cmp isn't defined in the blueprint as the bundled go-cmp is missing its go module file. I could get those files but can't get this command to run 
`go2bp -rewrite google.golang.org/protobuf=golang-protobuf -rewrite github.com/google/go-cmp/cmp=go-cmp -exclude-src internal/detrand/rand_test.go` 

the command is for regenerating Android.gen.bp for golang-protobuf but i can't summon it. supposedly it's part of build/soong command but I'm not sure how it can be run. Any idea before I give up on this source 😂

**Comment by KonstaT** [comment]
I though you already did (you should have at least). :) Why go with preview when there's actual releases now.

Just init the repo in the same directory again with a different branch/tag. You already have the source so it shouldn't take many minutes to sync.

**Comment by Road-Drum** [comment]
got it build but for whatever reason mke2fs fails when packing it into system.img

```
mke2fs 1.45.4 (23-Sep-2019)
Creating filesystem with 267288 4k blocks and 66960 inodes
Filesystem UUID: 2d3a033d-0d69-40dd-80d5-fb532e1cc641
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376

Allocating group tables: done                            
Writing inode tables: done                            
Writing superblocks and filesystem accounting information: done


__populate_fs: Could not allocate block in ext2 filesystem while writing file "SystemUI.apk"
e2fsdroid: Could not allocate block in ext2 filesystem while populating file system
```

already changed `BoardConfig.mk` to match and give more space to `BOARD_SYSTEMIMAGE_PARTITION_SIZE`. didn't even run out of space on storage. don't tell me I have to `make clean` ☹️

**Comment by KonstaT** [comment]
Haven't come across such issue. With a quick glance I couldn't see anything obvious wrong with android-rpi config. 1024MB for system partition does indeed seem small. I have double that on 64-bit builds and on the current LineageOS 19 build I have running 1.3GB is used.

I doubt `make clean` would help you with this anyway.

**Comment by Road-Drum** [comment]
strange that usually it calculates the exact bytes needed to put them into an image which for whatever reason the value isn't enough. android-rpi targets tv and the only packages that i'm aware apart from atv_base are just tvsettings and rplauncher so that explains the small size than lineage. if my build is enough, I'll propose changes needed on glodroid since tbh, I don't recall the original android-rpi is usable apart from being some kind of kiosk like android things

got it built now after guesstimating the system.img size. going to get some sleep and try flashing it later

**Comment by Road-Drum** [comment]
> I have double that on 64-bit builds and on the current LineageOS 19 

seeing that you have Lineage 19, does it boot to android? I got kernel booted up but it remain blank afterwards. even switched between your kernel and android-rpi's. I suppose the issue is similar to this https://github.com/android-rpi/device_arpi_rpi4/issues/86 though the person only adapt to r2 and make no changes on graphics like mine

guess it's time to get serial to usb connector for Pi. Always told myself that I don't have a usecase

**Comment by KonstaT** [comment]
All good with LineageOS 19 (which you'll find out sooner or later :)).

Yeah, you most definitely need a serial console adapter to do things like this. Could also be a separate issue with android-rpi like in the issue report.

**Comment by Road-Drum** [comment]
probably just me, but is there anything changed on cmdline when gbm_mesa and minigbm are used? I saw some changes on cmdline in glodroid `next` but unsure if that is required

**Comment by KonstaT** [comment]
No changes needed on cmdline.

It looks like android-rpi can support adb on USB-C if you uncomment https://github.com/android-rpi/device_arpi_rpi4/blob/arpi-12/boot/config.txt#L5. You'd need powered USB-C hub or USB Y-cable and outside power source for this. One last resort is to create a service to e.g. init.rpi4.rc that writes logcat to somewhere in /data partition.

BTW, one thing I noticed. Have you removed the frameworks/av fork from manifest (https://github.com/android-rpi/local_manifests/blob/arpi-12/default.xml#L5-L6) so you're using android-12.0.0_rX on that as well (one possible reason for the previously linked issue)?

**Comment by Road-Drum** [comment]
here's my default.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote name="arpi" fetch="https://github.com/android-rpi"/>
  <remote name="lineage-rpi" fetch="https://github.com/lineage-rpi"/>

  <!--remove-project name="platform/frameworks/av"/-->
  <!--project path="frameworks/av" name="frameworks_av" revision="arpi-12" remote="arpi"/-->
  <!--remove-project name="platform/packages/modules/NeuralNetworks"/-->
  <!--project path="packages/modules/NeuralNetworks" name="platform/packages/modules/NeuralNetworks"-->

  <remove-project name="platform/external/mesa3d"/>
  <remove-project name="platform/external/drm_hwcomposer"/>
  <remove-project name="platform/external/minigbm"/>
  <project path="external/mesa3d" name="android_external_mesa3d" revision="lineage-18.1" remote="lineage-rpi"/>
  <project path="external/drm_hwcomposer" name="android_external_drm_hwcomposer" revision="lineage-18.1" remote="lineage-rpi"/>
  <project path="external/minigbm" name="android_external_minigbm" revision="lineage-18.1" remote="lineage-rpi"/>

  <project path="hardware/arpi" name="hardware_arpi" revision="arpi-12" remote="arpi"/>
  <project path="device/arpi/rpi4" name="device_arpi_rpi4" revision="arpi-12" remote="arpi"/>

  <!--project path="vendor/arpi/RpLauncher" name="RpLauncher" revision="arpi-12" remote="arpi"/-->
</manifest>
```

I've already disabled forked `frameworks/av` and `NeuralNet`. `hardware/arpi` has been changed so that it doesn't build the older composer, allocator and mapper that relies on peyo-hd's drm_gralloc and hwcomposer. probably possible to drop it entirely as I don't see glodroid `next` using it at all

isn't adb through dwc2 means I'm powering the pi via host USB port? I still have PC that has USB 3.2 gen 1 that should be able to deliver enough power. I'll look at dumping via init.rpi4.rc in the meantime

btw it seems that I don't see anything got created in /userdata when using lineage-rpi kernel. I'll be rolling back with arpi one as it seems to generate stuff in userdata

**Comment by KonstaT** [comment]
Manifest looks fine (you can now switch to lineage-19.0 branches, though). The lineage-18.1 kernel won't work as is with Android 12 but there's now new one for that as well (make sure to use matching boot firmware - 5.4 vs. 5.10). My LineageOS 19 build is also out. https://konstakang.com/devices/rpi4/LineageOS19/

You probably still want audio HAL from hardware/arpi or there's other options as well. I'm using one based on one from hikey (https://github.com/lineage-rpi/android_device_brcm_rpi3/tree/lineage-15.1/audio).

There is something off spec with the USB-C on Pi 4 and I'm not sure if it was fixed on later hw revisions. I bought myself a fancy USB-C hub with power delivery and that doesn't of course work with my Pi 4. But yes, you need power on the USB-C as well.

I found this stashed away for logging:
```
service logging /system/bin/logcat -f /data/logcat.txt
    user system
    group system log
    class core
```

**Comment by Road-Drum** [comment]
thanks. Just downloaded your build and flashing on my sdcard. If I still can't figure it out, I'll just build lineage-rpi. lineage-17.1 branch of device_brcm_rpi4 shouldn't have too much changes for use with lineage 19 right?

speaking about the strange blank issue with android-rpi, I'm still doing a guesswork but is it possible because of how ramdisk is created? android-rpi used to build ramdisk and kernel separately but now everything is handled by android buildsystem. not to mention its manifest take AOSP kernel instead of its own (used to be its own kernel fork afaik back in android 9 and older)

**Comment by KonstaT** [comment]
Latest branch with complete sources is lineage-15.1 and on Pi 3 so pretty long way to go from that.

android-rpi is still a pretty decent reference but IMO it should be updated with the graphics drivers that are being mainlined. Wouldn't hurt to have a full Android UI either because Android TV strips away so many features.

AOSP doesn't support inline kernel build. That's only implemented on custom AOSP forks such as LineageOS. Don't see anything wrong with the android-rpi kernel manifest (https://github.com/android-rpi/kernel_manifest/blob/arpi-5.10/default.xml#L26).
