### ISSUE TITLE
LineageOS 19.0 (Android 12) source for RPI

### ISSUE THREAD

**Issue by mse6cob** [lineage-rpi/android_local_manifest#15]
@KonstaT :

I couldn't find repository for building Android 12 for RPI.

https://github.com/LineageOS/android/tree/lineage-19.0

Could you please share the link or steps.

Thanks.

**Comment by KonstaT** [comment]
https://github.com/lineage-rpi/android_local_manifest/issues/8#issuecomment-625031841

**Comment by ArtHsu** [comment]
> [#8 (comment)](https://github.com/lineage-rpi/android_local_manifest/issues/8#issuecomment-625031841)

Hi KonstaT,

[Question1] I still have no idea how to build Android12 for RPI4 by the link you provided. Can you have more detailed steps? Thanks.
The main issue now is that I don't have the right "manifest_brcm_rpi.xml" for LineageOS19.1.

[Question2] I've build Lineage17.1 for RPI4 successfully and boot the image from SD card. But after powered on, it only shows between a rainbow screen and a black screen. I have no idea how to solve the problem. Could you advise on this case? Thanks.
