### ISSUE TITLE
manifest_brcm_rpi.xml of LineageOS19.1 for RPI4

### ISSUE THREAD

**Issue by ArtHsu** [lineage-rpi/android_local_manifest#16]
[Question1] Could you kindly provide the manifest_brcm_rpi.xml of building LineageOS19.1 for RPI4? Thanks.
[Question2] I've used current file to build LineageOS17.1 for RPI4 successfully. But after booted up from SD card, the screen shows back and forth between a colored square and a black screen. Do you have any advise on the situation? Thanks.

**Comment by KonstaT** [comment]
1. There's no current plans to due reasons stated before. https://github.com/lineage-rpi/android_local_manifest/issues/8#issuecomment-625031841
2. I haven't provided complete sources for lineage-17.1 branch either.
