### ISSUE TITLE
How to build 'LineageOS 19 (Android 12L) for Raspberry Pi 4 B'?

### ISSUE THREAD

**Issue by fellow99** [lineage-rpi/android_local_manifest#17]
when I download manifest_brcm_rpi.xml by using:
`curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi.xml -O -L https://raw.githubusercontent.com/lineage-rpi/android_local_manifest/lineage-17.1/manifest_brcm_rpi.xml`

and
`lunch lineage_rpi4-userdebug`

"lineage_rpi4-userdebug" is not found.

**Comment by fellow99** [comment]
Another question is:

I had successfully built the LineageOS 17.1 on Pi4B, using these scripts:
`
repo init -u git://github.com/LineageOS/android.git -b lineage-17.1
curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi.xml -O -L https://raw.githubusercontent.com/lineage-rpi/android_local_manifest/lineage-17.1/manifest_brcm_rpi.xml
repo sync

. build/envsetup.sh
lunch lineage_rpi4-userdebug
mka

cd ./device/brcm/rpi4
sudo ./mkimg.sh
`

At last, it makes lineage-17.1-YYYYMMDD-rpi4.img

BUT, when I flashed img file into TF and start the PI as usual, It showed the rainbow screen and restarted.

What is the problem probably? @KonstaT

**Comment by KonstaT** [comment]
https://github.com/lineage-rpi/android_local_manifest/issues/8#issuecomment-625031841
