### ISSUE TITLE
Safetynet fixes from Protonaosp

### ISSUE THREAD

**Issue by z2z** [lineage-rpi/android_local_manifest#18]
Please check if this patches could be integrated from https://protonaosp.org/developers/details/safetynet with any Android certified device props will help to pass safetynet without need for magisk.

**Comment by KonstaT** [comment]
Thanks for the information but my stance is the same as https://lineageos.org/Safetynet/ i.e. "not intentionally circumvent an integrity check that Google has put in place for app developers".

Yes, you can get around this by using Magisk or ih8sn (https://github.com/luk1337/ih8sn) but spoofing SafetyNet is not something I should nor plan to do with the Android images I'm releasing.
