### ISSUE TITLE
Issues with Lineage Android TV 19.1 on RPi 4 B

### ISSUE THREAD

**Issue by PrimoDev23** [lineage-rpi/android_local_manifest#19]
I just installed named OS from your website on my new RPi 4 B and faced an issue where I could not select any setting except network settings. I then searched for the sources and wanted to try to build it from scratch with updated lineage sources, but there are no sources. Lineage 20 ATV worked fine, but there are no google apps and my mouse is teribly laggy (probably not a ROM issue, so not gonna blame you on that). So I really appreciate your work and I can fully understand that it's frustrating and against open source terms to sell this, but it's also kind of against the open source terms to keep the source closed.
So you should either provide more up to date builds or make the sources public so others can contribute or at least update things.
And before saying I have no clue or whatever, check my kernel repositories all having clean history, own ports, features that were sometimes "stolen" by others, but that's the way of open source.

**Comment by KonstaT** [comment]
Android TV is not intended to be used with a mouse or a touchscreen. You need to have a remote to navigate the system (USB remote, Bluetooth remote, IR remote, TV's remote using HDMI-CEC, arrow keys on your keyboard, etc).

If you want to build complete AOSP (or something AOSP-based) for the Pi 4 you can look into the Raspberry Vanilla (https://github.com/raspberry-vanilla) source code I've released.

Selling open source software is perfectly fine (it's even exactly what every Android manufacturer is doing). Not complying with open source licensing while doing so is not. And no, it's also not against open source terms to keep some things closed source if the licensing doesn't require it (e.g. Apache 2.0 - again exactly what every Android manufacturer is doing).
