### ISSUE TITLE
Opengl application always crash !!!

### ISSUE THREAD

**Issue by wellcomez** [lineage-rpi/android_local_manifest#2]
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
E/AndroidRuntime: FATAL EXCEPTION: GLThread 370
                  Process: com.brush.opengldemo, PID: 10473
                  java.lang.IllegalArgumentException: No configs match configSpec
                      at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:877)
                      at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1412)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

**Comment by KonstaT** [comment]
https://github.com/android-rpi/device_brcm_rpi3/wiki#enable-glsurfaceview

There's various issues with display because of this.

**Comment by wellcomez** [comment]
Now I'm using official lineage-14.1-20180118-UNOFFICIAL-KonstaKANG-rpi3.img from http://konstakang.com/devices/rpi3/CM14.1/.
Same problem still exists.  I have changed my code       `  setEGLConfigChooser(8, 8, 8, 8, 16, 0);  or  setEGLConfigChooser(8, 8, 8, 8, 24, 0);`, app still crash.

**Comment by wellcomez** [comment]
Now I'm using official lineage-14.1-20180118-UNOFFICIAL-KonstaKANG-rpi3.img from http://konstakang.com/devices/rpi3/CM14.1/.
Same problem still exists. I have changed my code setEGLConfigChooser(8, 8, 8, 8, 16, 0); or setEGLConfigChooser(8, 8, 8, 8, 24, 0);, app still crash.

I have similar problem at android-rpi/device_brcm_rpi3#51

**Comment by KonstaT** [comment]
Yes, I know. For the exact same reason wallpaper is not displayed and included gallery app crashes (among other issues). You're welcome to contribute and look into how this can be resolved.

**Comment by wellcomez** [comment]
I've found solution.  Opengl version should be 2 `setEGLContextClientVersion(2);`

**Comment by KonstaT** [comment]
This crash specifically should be fixed in 20180817 release. https://github.com/lineage-rpi/android_local_manifest/blob/cm-14.1/patches/frameworks_base/0002-rpi3-GLSurfaceView-Be-less-picky-about-EGLConfig-alp.patch
