### ISSUE TITLE
Lineageos 20 build for rpi 4 and opengl es 3.2

### ISSUE THREAD

**Issue by kareig** [lineage-rpi/android_local_manifest#20]
How to enable opengl es 3.2 ? 

According to the docs it is capable.
“ The GPU bundled with Raspberry Pi 4 is a VideoCore VI capable of OpenGL ES 3.2, a significant step above the VideoCore IV present in Raspberry Pi 3 which could only do OpenGL ES 2.0.”

**Comment by KonstaT** [comment]
I'm not really involved in the graphics driver development and I doubt there's anything Android specific here. This is something that you would need to ask Mesa folks and/or people over at Igalia who have been contracted to do the graphics driver development for the VideoCore GPUs used on Raspberry Pi.
