### ISSUE TITLE
64bit rpi4 Targets

### ISSUE THREAD

**Issue by itforgeuk** [lineage-rpi/android_local_manifest#21]
Are arm64 Raspberry Pi 4  targets supported?

I tried to change the "BoardConfigCommon.mk" but I had no luck

**Comment by KonstaT** [comment]
See Raspberry Vanilla project for AOSP device specific implementation for Raspberry Pi.
https://github.com/raspberry-vanilla

All releases for Raspberry Pi since Android 11 are 64-bit/32-bit multilib builds.
https://source.android.com/docs/setup/create/64-bit-builds
