### ISSUE TITLE
There's error about dev mapper when ./mkimg.sh

### ISSUE THREAD

**Issue by princeofgiri** [lineage-rpi/android_local_manifest#3]
I use Debian 9 and 18.04 and the error was similiar
`
ridon@download:~/ridon/system/device/brcm/rpi3$ sudo ./mkimg.sh 
[sudo] password for ridon: 
Creating image file lineage-14.1-20180601-rpi3.img...
8192+0 records in
8192+0 records out
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 4.82897 s, 889 MB/s
Creating partitions...
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
device mapper prerequisites not met

Welcome to fdisk (util-linux 2.29.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

fdisk: cannot open /dev/loop0: No such file or directory
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
device mapper prerequisites not met
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
device mapper prerequisites not met
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: unable to open /dev/mapper/loop0p1: No such file or directory
mke2fs 1.43.4 (31-Jan-2017)
The file /dev/mapper/loop0p3 does not exist and no size was specified.
Copying system...
dd: error writing '/dev/mapper/loop0p2': No space left on device
1+0 records in
0+0 records out
503808 bytes (504 kB, 492 KiB) copied, 0.00143976 s, 350 MB/s
Copying boot...
mount: special device /dev/mapper/loop0p1 does not exist
umount: /dev/mapper/loop0p1: mountpoint not found
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
device mapper prerequisites not met
Done, created lineage-14.1-20180601-rpi3.img!
`
Any clue about this?

**Comment by KonstaT** [comment]
Works for me with Ubuntu 16.04.

Something wrong with mapper in your end?
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
device mapper prerequisites not met

**Comment by freesamael** [comment]
I don't know about Debian, but on my Ubuntu 18.04 it seems a lot of loop devices have been added by snap so the script failed:
```
❯ /sbin/losetup --list
NAME        SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                                                      DIO LOG-SEC
/dev/loop15         0      0         1  1 /var/lib/snapd/snaps/gtk-common-themes_319.snap                                  0     512
/dev/loop1          0      0         1  1 /var/lib/snapd/snaps/core_4830.snap                                              0     512
/dev/loop13         0      0         1  1 /var/lib/snapd/snaps/gnome-3-26-1604_64.snap                                     0     512
/dev/loop11         0      0         1  1 /var/lib/snapd/snaps/gnome-calculator_178.snap                                   0     512
/dev/loop8          0      0         1  1 /var/lib/snapd/snaps/core_4917.snap                                              0     512
/dev/loop6          0      0         1  1 /var/lib/snapd/snaps/gnome-calculator_175.snap                                   0     512
/dev/loop18         0      0         1  1 /var/lib/snapd/snaps/gnome-logs_34.snap                                          0     512
/dev/loop4          0      0         1  1 /var/lib/snapd/snaps/gnome-logs_37.snap                                          0     512
/dev/loop16         0      0         1  1 /var/lib/snapd/snaps/gnome-characters_103.snap                                   0     512
/dev/loop2          0      0         1  1 /var/lib/snapd/snaps/gnome-characters_101.snap                                   0     512
/dev/loop14         0      0         1  1 /var/lib/snapd/snaps/gnome-system-monitor_51.snap                                0     512
/dev/loop0          0      0         1  1 /var/lib/snapd/snaps/core_4650.snap                                              0     512
/dev/loop12         0      0         1  1 /var/lib/snapd/snaps/gnome-characters_96.snap                                    0     512
/dev/loop9          0      0         1  1 /var/lib/snapd/snaps/gnome-system-monitor_45.snap                                0     512
/dev/loop20         0      0         0  0 /development/rpi3/lineage-15.1/device/brcm/rpi3/lineage-15.1-20180802-rpi3.img   0     512
/dev/loop10         0      0         1  1 /var/lib/snapd/snaps/gnome-logs_25.snap                                          0     512
/dev/loop7          0      0         1  1 /var/lib/snapd/snaps/docker_179.snap                                             0     512
/dev/loop19         0      0         1  1 /var/lib/snapd/snaps/gnome-system-monitor_41.snap                                0     512
/dev/loop5          0      0         1  1 /var/lib/snapd/snaps/gnome-calculator_180.snap                                   0     512
/dev/loop17         0      0         1  1 /var/lib/snapd/snaps/gnome-3-26-1604_70.snap                                     0     512
/dev/loop3          0      0         1  1 /var/lib/snapd/snaps/gnome-3-26-1604_59.snap                                     0     512
```

**Comment by freesamael** [comment]
Not very familiar with shell script. Is there a smarter way to get the looper device than adding
`losetup  | grep $IMGNAME | awk '{print $1}' | sed 's/dev/dev\/mapper/'` to the script?

**Comment by KonstaT** [comment]
Yeah, came across the same issue with snap packages and loop devices with Ubuntu 16.04 as well after recent updates.

Will check your pull request when I get around. Will test later but looks good to me AFAICT. Thanks. :)

**Comment by KonstaT** [comment]
Closing this as this should now work on Ubuntu 16.04 LTS and 18.04 LTS at least.
