### ISSUE TITLE
Whether there are plans to support lineage-16 ?

### ISSUE THREAD

**Issue by Pillar1989** [lineage-rpi/android_local_manifest#4]
...

**Comment by KonstaT** [comment]
There's already lineage-16.0 branches in all the device specific repos. Using lineage-15.1 local manifest, instructions, etc apply if you adapt the guide to lineage-16.0 branch where necessary.

I haven't still pushed all the device changes for Pie so it takes a little work to get it built, booted, and working.

**Comment by Pillar1989** [comment]
Android Pie recommends that HIDL be used to deploy the manufacturer's devices.  There is a lot of work to be done.

**Comment by KonstaT** [comment]
I am not an OEM so passing CTS or Google certification doesn't really concern me.

There's a lot work to be done even with basic functionality (GPU/graphics, bluetooth, etc). This being open source, you're of course more than welcome to do that work!
