### ISSUE TITLE
Hi,when I compile this code ,it has problem

### ISSUE THREAD

**Issue by IngenicC** [lineage-rpi/android_local_manifest#6]
build/make/core/product_config.mk:234: error: Can not locate config makefile for product "lineage_rpi3".
21:20:36 dumpvars failed with: exit status 1
Device rpi3 not found. Attempting to retrieve device repository from LineageOS Github ([http://github.com/LineageOS](https://github.com/LineageOS)).
Repository for rpi3 not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/make/core/product_config.mk:234: error: Can not locate config makefile for product "lineage_rpi3".
21:20:39 dumpvars failed with: exit status 1
build/make/core/product_config.mk:234: error: Can not locate config makefile for product "lineage_rpi3".
21:20:40 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_rpi3'
** Do you have the right repo manifest?

**Comment by KonstaT** [comment]
It looks like you haven't synced the device specific trees.

Did you add the local manifest like it's instructed in 'Initialize repo' section of the readme?

**Comment by IngenicC** [comment]
hi
I add  use code ，but it does not  work

repo init -u git://github.com/LineageOS/android.git -b lineage-16.0
git clone https://github.com/LineageOS-PI/android_.repo_local_manifests .repo/local_manifests -b lineage-16.0
repo sync

**Comment by KonstaT** [comment]
I haven't released lineage-16.0 branches for Raspberry Pi.

Sorry, that's not my instructions so it's not my problem either. Generally speaking you need to have the local manifest in the right place and 'repo sync' after adding the manifest so the device specific parts are synced as well.
