### ISSUE TITLE
Issue in building.

### ISSUE THREAD

**Issue by skand24** [lineage-rpi/android_local_manifest#7]
I have used below command for repo 
`repo init -u git://github.com/LineageOS/android.git -b lineage-16.0 && 
curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi.xml -O -L https://raw.githubusercontent.com/lineage-rpi/android_local_manifest/lineage-16.0/manifest_brcm_rpi.xml && repo sync`

For building :
source build/envsetup.sh
lunch lineage_rpi4-userdebug
(After this I dont know its error or warning **Trying dependencies-only mode on a non-existing device tree?** )
make -j8

but I am getting below error:

> PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20200428-UNOFFICIAL-rpi4
TARGET_PRODUCT=lineage_rpi4
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-96-generic-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/home/skand/lineage-rpi/out
WITH_SU=true
============================================
ninja: no work to do.
ninja: no work to do.
No need to regenerate ninja file
No need to regenerate ninja file
ninja: error: 'prebuilts/lineage-sdk/api/9.txt', needed by '/home/skand/lineage-rpi/out/target/common/obj/PACKAGING/checkpublicapi-lineage-last-timestamp', missing and no known rule to make it
16:26:19 ninja failed with: exit status 1

and if mka systemimage

> [ 99% 101/102] Target system fs image: /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system.img
FAILED: /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system.img 
/bin/bash -c "(mkdir -p /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/ /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates && rm -rf /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs.sh\" >>  /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"selinux_fc=/home/skand/lineage-rpi/out/target/product/rpi4/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"skip_fsck=true\" >>  /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (PATH=\$PATH build/make/tools/releasetools/build_image.py /home/skand/lineage-rpi/out/target/product/rpi4/system /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system_image_info.txt /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/system.img /home/skand/lineage-rpi/out/target/product/rpi4/system /home/skand/lineage-rpi/out/target/product/rpi4/obj/PACKAGING/systemimage_intermediates/generated_system_image_info.txt || ( mkdir -p /home/skand/lineage-rpi/out/dist; cp /home/skand/lineage-rpi/out/target/product/rpi4/installed-files.txt /home/skand/lineage-rpi/out/dist/installed-files-rescued.txt; exit 1 ) )"
Traceback (most recent call last):
  File "build/make/tools/releasetools/build_image.py", line 1075, in <module>
    main(sys.argv[1:])
  File "build/make/tools/releasetools/build_image.py", line 1064, in main
    if not BuildImage(in_dir, image_properties, out_file, target_out):
  File "build/make/tools/releasetools/build_image.py", line 645, in BuildImage
    prop_dict["image_size"] = prop_dict["partition_size"]
KeyError: 'partition_size'
ninja: build stopped: subcommand failed.
16:30:32 ninja failed with: exit status 1

Please let me know what I am doing wrong

**Comment by KonstaT** [comment]
lineage-16.0 branch only has skeleton device tree that you can use to build the kernel (mka kernel).

**Comment by skand24** [comment]
Then which branch I will use for building rpi4
