### ISSUE TITLE
USB camera and mesa v3d

### ISSUE THREAD

**Issue by rsglobal** [lineage-rpi/android_local_manifest#9]
@KonstaT ,

Hello,
Can you please check will camera work for you with this patch?
https://github.com/GloDroid/glodroid_forks/commit/73b4d0094ed2defdfe4e662eb9b58516cb2e3123

**Comment by KonstaT** [comment]
Hi.

Thanks for letting me know. :)

Unfortunately this doesn't fix the issue I'm having with camera. It seems there's an issue with the default camera app (and maybe some other camera apps as well?). Some third party camera apps seem to work fine (e.g. OpenCamera works and I've seen people use camera with WhatsApp video calls, Zoom, etc).

I'm using the official Pi camera module but the results are the same with the cheap UVC USB webcam I have. Android-x86 camera HAL is used in my builds with some minor modifications to add resolutions for the Pi camera modules if you want to test things with GloDroid yourself.

**Comment by rsglobal** [comment]
Thanks you for testing.

In case of some shared (between your project and GloDroid) issues feel free to report them to us.
It will help to boost both projects.

I will appreciate you if you can share your camera HAL.

**Comment by KonstaT** [comment]
I left you couple of comments on your mesa patches.
https://github.com/rsglobal/glodroid_forks/commit/e2b75435ce4ab84eb6de227629cdc27970fca5a2#commitcomment-41334934
https://github.com/rsglobal/glodroid_forks/commit/f2ce0b24848dc49a6400c6a299e8b46487862270#commitcomment-41335009

I've attached the camera HAL ([camera.zip](https://github.com/lineage-rpi/android_local_manifest/files/5050450/camera.zip)).
It's a fork of https://osdn.net/projects/android-x86/scm/git/hardware-libcamera/tree/pie-x86/ with very minor modifications.

device.mk:
```
PRODUCT_PACKAGES += \
    android.hardware.camera.provider@2.4-impl \
    android.hardware.camera.provider@2.4-service \
    camera.rpi
```

manifest.xml:
```
    <hal format="hidl">
        <name>android.hardware.camera.provider</name>
        <transport>hwbinder</transport>
        <version>2.4</version>
        <interface>
            <name>ICameraProvider</name>
            <instance>legacy/0</instance>
        </interface>
    </hal>
```

uevent:
`/dev/video*  0660  system  camera`

system.prop:
`ro.hardware.camera=rpi`
or rename the HAL to match your ro.board.platform

config.txt:
```
gpu_mem=128
start_x=1
```
and you'll need the extended boot firmware files for Pi camera modules as well

On kernel side you'll need
```
CONFIG_USB_VIDEO_CLASS=y
CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y
```
for USB webcams and
```
CONFIG_VIDEO_BCM2835=y
CONFIG_BCM2835_VCHIQ_MMAL=y
CONFIG_BCM_VC_SM_CMA=y
```
for Pi camera modules.

**Comment by rsglobal** [comment]
Thank you for the HAL,
I've found that external cameras does not require HAL.
https://source.android.com/devices/camera/external-usb-cameras

**Comment by KonstaT** [comment]
At least I couldn't get my UVC webcam working with the AOSP external USB camera HAL when I tested it with Android 9 (haven't tested with 10). There's also this (https://android.googlesource.com/platform/hardware/libhardware/+/refs/tags/android-10.0.0_r41/modules/camera/3_4/README.md) but didn't have much luck with that either.

Android-x86 camera HAL works with both the Pi camera modules and USB webcams which is great.
